version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3
    cooldown:
      semver-major-days: 40
      semver-minor-days: 12
      semver-patch-days: 7
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      react-router:
        patterns:
          - "react-router"
          - "@react-router/*"
      tailwind:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
      dev-dependencies:
        dependency-type: "development"
        exclude-patterns:
          - "@biomejs/biome"
          - "vite"
          - "typescript"
          - "@playwright/test"
          - "@types/react"
          - "@types/react-dom"
          - "@react-router/*"
          - "tailwindcss"
          - "@tailwindcss/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "jadatkins"
    groups:
      actions:
        patterns:
          - "*"
