services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      # Mount source code for development (optional - remove for production-like testing)
      - .:/app
      - /app/node_modules
      - /app/.yarn/cache